# Generated by Django 3.1.3 on 2020-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_name', models.CharField(max_length=20)),
                ('total_evaluation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('total_evaluation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valuelec_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_name', models.CharField(max_length=20)),
                ('teacher_name', models.CharField(max_length=20)),
                ('total_evaluation', models.IntegerField()),
                ('lec_simplicity', models.IntegerField()),
                ('credit_simplicity', models.IntegerField()),
                ('task_smallness', models.IntegerField()),
                ('class_style', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
