# Generated by Django 3.1.3 on 2020-11-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuelec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuelec_register',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='class_style',
            field=models.IntegerField(choices=[(1, '非同期'), (2, '同期or対面'), (3, '同期と非同期両方')], default=1, verbose_name='授業形態'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='credit_simplicity',
            field=models.IntegerField(verbose_name='単位の取りやすさ'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='lec_name',
            field=models.CharField(max_length=20, verbose_name='講義名'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='lec_simplicity',
            field=models.IntegerField(verbose_name='講義の簡単さ'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='task_smallness',
            field=models.IntegerField(verbose_name='課題の少なさ'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='teacher_name',
            field=models.CharField(max_length=20, verbose_name='教授名'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='total_evaluation',
            field=models.IntegerField(verbose_name='総合評価'),
        ),
    ]
