# Generated by Django 3.1.3 on 2020-11-22 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuelec', '0002_auto_20201120_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='valuelec_register',
            name='lec_name',
        ),
        migrations.RemoveField(
            model_name='valuelec_register',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher_name',
            field=models.CharField(default='安倍晋三', max_length=20, validators=[django.core.validators.RegexValidator(message='氏名は漢字・ひらがな・カタカナのみとし、氏と名の間に全角スペースを入れてください', regex='^[ぁ-んァ-ヶー一-龠]+\u3000[ぁ-んァ-ヶー一-龠]+$')], verbose_name='教授名'),
        ),
        migrations.AddField(
            model_name='valuelec_register',
            name='lec_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lec_name',
            field=models.CharField(default='算数', max_length=20, validators=[django.core.validators.RegexValidator(message='講義名は漢字・ひらがな・カタカナのみです', regex='^[ぁ-んァ-ヶー一-龠]+$')], verbose_name='講義名'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='credit_simplicity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='単位の取りやすさ'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='lec_simplicity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='講義の簡単さ'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='task_smallness',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='課題の少なさ'),
        ),
        migrations.AlterField(
            model_name='valuelec_register',
            name='total_evaluation',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='総合評価'),
        ),
    ]
